---
# tasks file for Opdracht 1
- name: Apache installatie
  apt:
    name: apache2
    state: present
    update_cache: yes
  notify: restart apache

- name: PHP installatie
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Apache activatie check
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: PHP testpagina
  ansible.builtin.copy:
    dest: /var/www/html/index.php
    content: "<?Week 4 Opdracht 1 Bas Maarschalkerweerd :)(); ?>"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Mysql installatie
  ansible.builtin.apt:
    name: mysql-client
    state: present
    update_cache: yes